-- GENERATED by fixtures/gen-seed.ts from fixtures/seed.json. Do not edit.

INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change, email_change_token_new,
  email_change_token_current, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '11111111-1111-4111-8111-111111111111', 'authenticated', 'authenticated', 'alice@example.com',
  extensions.crypt('password123', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(),
  '', '', '', '', '', ''
);
INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (
  gen_random_uuid(), '11111111-1111-4111-8111-111111111111', '11111111-1111-4111-8111-111111111111',
  jsonb_build_object('sub', '11111111-1111-4111-8111-111111111111', 'email', 'alice@example.com', 'email_verified', true),
  'email', now(), now(), now()
);

INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change, email_change_token_new,
  email_change_token_current, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '22222222-2222-4222-8222-222222222222', 'authenticated', 'authenticated', 'bob@example.com',
  extensions.crypt('password123', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(),
  '', '', '', '', '', ''
);
INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (
  gen_random_uuid(), '22222222-2222-4222-8222-222222222222', '22222222-2222-4222-8222-222222222222',
  jsonb_build_object('sub', '22222222-2222-4222-8222-222222222222', 'email', 'bob@example.com', 'email_verified', true),
  'email', now(), now(), now()
);

INSERT INTO public.people (id, name, nickname, score, rating, active, born, created_at, meta) VALUES
  (1, 'Alice', 'Al', 10, 4.5, true, '1990-01-15', '2024-01-15T10:30:00+00:00', '{"team":"red","level":3}'::jsonb),
  (2, 'alice', NULL, NULL, 3.25, false, '1991-02-20', '2024-01-15T15:30:00+05:00', '{"team":"blue"}'::jsonb),
  (3, 'ALICE', 'AL', 7, NULL, true, NULL, '2024-02-01T00:00:00Z', NULL),
  (4, 'Bob', 'Bobby', 5, 2, true, '1985-12-31', '2024-03-10 08:00:00+00', '{"team":"red","tags":["a","b"]}'::jsonb),
  (5, 'Émile', 'Em', 12, 4.75, false, '1979-07-04', '2024-03-11T12:00:00.123456+00:00', '{}'::jsonb),
  (6, 'émile', NULL, NULL, 1.1, true, NULL, '2024-03-12T12:00:00+00:00', '{"team":"green"}'::jsonb),
  (7, 'Straße', 'Str', 3, 3, true, '2000-05-05', '2024-04-01T09:15:00-07:00', '{"team":"blue","level":1}'::jsonb),
  (8, 'Carol, Jr.', 'C, J', 8, 3.5, false, '1995-09-09', '2024-04-02T00:00:00+00:00', '{"team":"red"}'::jsonb),
  (9, 'Dave', 'D%_', 0, 0, true, '1988-08-08', '2024-05-01T23:59:59+00:00', '{"level":2}'::jsonb),
  (10, 'Zoë', 'Zo', 15, 5, false, '2001-11-11', '2024-06-30T12:00:00+00:00', '{"team":"green","level":5}'::jsonb);

INSERT INTO public.authors (id, name) VALUES
  (1, 'Ada'),
  (2, 'Grace'),
  (3, 'Linus');

INSERT INTO public.posts (id, author_id, title, published) VALUES
  (1, 1, 'Engines', true),
  (2, 1, 'Notes on Babbage', false),
  (3, 2, 'Compilers', true),
  (4, 2, 'COBOL', true),
  (5, 3, 'Kernels', false);

INSERT INTO public.comments (id, post_id, body) VALUES
  (1, 1, 'Brilliant'),
  (2, 1, 'Ahead of its time'),
  (3, 3, 'Very readable'),
  (4, 4, 'Still running'),
  (5, 4, 'Legacy!');

INSERT INTO public.notes (id, owner_id, body, is_public) VALUES
  (1, '11111111-1111-4111-8111-111111111111', 'alice public', true),
  (2, '11111111-1111-4111-8111-111111111111', 'alice private', false),
  (3, '22222222-2222-4222-8222-222222222222', 'bob public', true),
  (4, '22222222-2222-4222-8222-222222222222', 'bob private', false);

SELECT setval(pg_get_serial_sequence('public.people', 'id'), greatest((SELECT coalesce(max(id), 0) FROM public.people), 1), (SELECT count(*) > 0 FROM public.people));

SELECT setval(pg_get_serial_sequence('public.authors', 'id'), greatest((SELECT coalesce(max(id), 0) FROM public.authors), 1), (SELECT count(*) > 0 FROM public.authors));

SELECT setval(pg_get_serial_sequence('public.posts', 'id'), greatest((SELECT coalesce(max(id), 0) FROM public.posts), 1), (SELECT count(*) > 0 FROM public.posts));

SELECT setval(pg_get_serial_sequence('public.comments', 'id'), greatest((SELECT coalesce(max(id), 0) FROM public.comments), 1), (SELECT count(*) > 0 FROM public.comments));

SELECT setval(pg_get_serial_sequence('public.notes', 'id'), greatest((SELECT coalesce(max(id), 0) FROM public.notes), 1), (SELECT count(*) > 0 FROM public.notes));

SELECT setval(pg_get_serial_sequence('public.scratch', 'id'), greatest((SELECT coalesce(max(id), 0) FROM public.scratch), 1), (SELECT count(*) > 0 FROM public.scratch));
