/**
 * seed.json → SQL for both databases, so both sides always hold identical data.
 *
 *   npx tsx fixtures/gen-seed.ts          write the generated files
 *   npx tsx fixtures/gen-seed.ts --check  fail if they are out of date (CI)
 *
 * Writes:
 *   supabase/migrations/00000000000000_schema.sql  (copy of schema.pg.sql)
 *   supabase/seed.sql                              (Postgres INSERTs + auth users)
 *   fixtures/seed.sqlite.sql                       (SQLite INSERTs)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

type Value = null | boolean | number | string | Value[] | { [k: string]: Value };
type Row = Record<string, Value>;
export interface Seed {
  users: { id: string; email: string; password: string }[];
  tables: Record<string, Row[]>;
}
export type Dialect = 'pg' | 'sqlite';

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
export const seed: Seed = JSON.parse(readFileSync(here('./seed.json'), 'utf8'));

const quote = (s: string) => `'${s.replace(/'/g, "''")}'`;

export function literal(v: Value, d: Dialect): string {
  if (v === null) return 'NULL';
  if (typeof v === 'boolean') return d === 'pg' ? String(v) : v ? '1' : '0';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') return quote(v);
  return d === 'pg' ? `${quote(JSON.stringify(v))}::jsonb` : quote(JSON.stringify(v));
}

export function insertsFor(d: Dialect, data: Seed = seed): string {
  const out: string[] = [];
  const schema = d === 'pg' ? 'public.' : '';
  for (const [table, rows] of Object.entries(data.tables)) {
    if (rows.length === 0) continue;
    const cols = Object.keys(rows[0]!);
    const values = rows.map((r) => `  (${cols.map((c) => literal(r[c] ?? null, d)).join(', ')})`);
    out.push(`INSERT INTO ${schema}${table} (${cols.join(', ')}) VALUES\n${values.join(',\n')};`);
  }
  if (d === 'pg') {
    // Explicit ids do not advance identity sequences; move them past the seed.
    for (const table of Object.keys(data.tables)) {
      out.push(
        `SELECT setval(pg_get_serial_sequence('public.${table}', 'id'), ` +
          `greatest((SELECT coalesce(max(id), 0) FROM public.${table}), 1), ` +
          `(SELECT count(*) > 0 FROM public.${table}));`,
      );
    }
  }
  return out.join('\n\n') + '\n';
}

/** Fixed-uuid users for GoTrue, so RLS cases see the same auth.uid() on both sides. */
export function authUsersPg(data: Seed = seed): string {
  return data.users
    .map(
      (u) => `INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change, email_change_token_new,
  email_change_token_current, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', ${quote(u.id)}, 'authenticated', 'authenticated', ${quote(u.email)},
  extensions.crypt(${quote(u.password)}, extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(),
  '', '', '', '', '', ''
);
INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (
  gen_random_uuid(), ${quote(u.id)}, ${quote(u.id)},
  jsonb_build_object('sub', ${quote(u.id)}, 'email', ${quote(u.email)}, 'email_verified', true),
  'email', now(), now(), now()
);`,
    )
    .join('\n\n');
}

const HEADER = '-- GENERATED by fixtures/gen-seed.ts from fixtures/seed.json. Do not edit.\n\n';

export function generatedFiles(): Record<string, string> {
  return {
    [here('../supabase/migrations/00000000000000_schema.sql')]:
      '-- GENERATED: copy of fixtures/schema.pg.sql. Edit that file, then run `npm run seed`.\n\n' +
      readFileSync(here('./schema.pg.sql'), 'utf8'),
    [here('../supabase/seed.sql')]: HEADER + authUsersPg() + '\n\n' + insertsFor('pg'),
    [here('./seed.sqlite.sql')]: HEADER + insertsFor('sqlite'),
  };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [path, body] of Object.entries(generatedFiles())) {
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {}
    if (current === body) continue;
    if (check) {
      console.error(`stale: ${path}`);
      stale++;
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, body);
      console.log(`wrote ${path}`);
    }
  }
  if (stale) {
    console.error('Generated seed files are out of date. Run `npm run seed`.');
    process.exit(1);
  }
}
