-- Postgres schema for the REFERENCE side (supabase start).
-- Keep table/column names identical to schema.sqlite.sql.
-- gen-seed.ts copies this file to supabase/migrations/ so `supabase start` applies it.

create table public.people (
  id         bigint generated by default as identity primary key,
  name       text not null,
  nickname   text,
  score      integer,
  rating     numeric(6, 2),
  active     boolean not null default true,
  born       date,
  created_at timestamptz not null default now(),
  meta       jsonb
);

create table public.authors (
  id   bigint generated by default as identity primary key,
  name text not null
);

create table public.posts (
  id        bigint generated by default as identity primary key,
  author_id bigint not null references public.authors (id),
  title     text not null,
  published boolean not null default false
);

create table public.comments (
  id      bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  body    text not null
);

create table public.notes (
  id        bigint generated by default as identity primary key,
  owner_id  uuid not null,
  body      text not null,
  is_public boolean not null default false
);

-- Write target. Starts empty; cases clean up after themselves.
create table public.scratch (
  id    bigint generated by default as identity primary key,
  label text not null unique,
  qty   integer,
  done  boolean not null default false,
  due   date,
  code  varchar(5)
);

-- Explicit grants: do not rely on platform default privileges.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- RLS. Read-only fixtures are open for reads only; scratch is fully open; notes is per-user.
alter table public.people   enable row level security;
alter table public.authors  enable row level security;
alter table public.posts    enable row level security;
alter table public.comments enable row level security;
alter table public.notes    enable row level security;
alter table public.scratch  enable row level security;

create policy people_read   on public.people   for select to anon, authenticated using (true);
create policy authors_read  on public.authors  for select to anon, authenticated using (true);
create policy posts_read    on public.posts    for select to anon, authenticated using (true);
create policy comments_read on public.comments for select to anon, authenticated using (true);

create policy scratch_all on public.scratch for all to anon, authenticated using (true) with check (true);

create policy notes_anon_read on public.notes for select to anon using (is_public);
create policy notes_auth_read on public.notes for select to authenticated
  using (is_public or owner_id = auth.uid());
create policy notes_auth_insert on public.notes for insert to authenticated
  with check (owner_id = auth.uid());
create policy notes_auth_update on public.notes for update to authenticated
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy notes_auth_delete on public.notes for delete to authenticated
  using (owner_id = auth.uid());
