-- GENERATED by fixtures/gen-seed.ts from fixtures/seed.json. Do not edit.

INSERT INTO people (id, name, nickname, score, rating, active, born, created_at, meta) VALUES
  (1, 'Alice', 'Al', 10, 4.5, 1, '1990-01-15', '2024-01-15T10:30:00+00:00', '{"team":"red","level":3}'),
  (2, 'alice', NULL, NULL, 3.25, 0, '1991-02-20', '2024-01-15T15:30:00+05:00', '{"team":"blue"}'),
  (3, 'ALICE', 'AL', 7, NULL, 1, NULL, '2024-02-01T00:00:00Z', NULL),
  (4, 'Bob', 'Bobby', 5, 2, 1, '1985-12-31', '2024-03-10 08:00:00+00', '{"team":"red","tags":["a","b"]}'),
  (5, 'Émile', 'Em', 12, 4.75, 0, '1979-07-04', '2024-03-11T12:00:00.123456+00:00', '{}'),
  (6, 'émile', NULL, NULL, 1.1, 1, NULL, '2024-03-12T12:00:00+00:00', '{"team":"green"}'),
  (7, 'Straße', 'Str', 3, 3, 1, '2000-05-05', '2024-04-01T09:15:00-07:00', '{"team":"blue","level":1}'),
  (8, 'Carol, Jr.', 'C, J', 8, 3.5, 0, '1995-09-09', '2024-04-02T00:00:00+00:00', '{"team":"red"}'),
  (9, 'Dave', 'D%_', 0, 0, 1, '1988-08-08', '2024-05-01T23:59:59+00:00', '{"level":2}'),
  (10, 'Zoë', 'Zo', 15, 5, 0, '2001-11-11', '2024-06-30T12:00:00+00:00', '{"team":"green","level":5}');

INSERT INTO authors (id, name) VALUES
  (1, 'Ada'),
  (2, 'Grace'),
  (3, 'Linus');

INSERT INTO posts (id, author_id, title, published) VALUES
  (1, 1, 'Engines', 1),
  (2, 1, 'Notes on Babbage', 0),
  (3, 2, 'Compilers', 1),
  (4, 2, 'COBOL', 1),
  (5, 3, 'Kernels', 0);

INSERT INTO comments (id, post_id, body) VALUES
  (1, 1, 'Brilliant'),
  (2, 1, 'Ahead of its time'),
  (3, 3, 'Very readable'),
  (4, 4, 'Still running'),
  (5, 4, 'Legacy!');

INSERT INTO notes (id, owner_id, body, is_public) VALUES
  (1, '11111111-1111-4111-8111-111111111111', 'alice public', 1),
  (2, '11111111-1111-4111-8111-111111111111', 'alice private', 0),
  (3, '22222222-2222-4222-8222-222222222222', 'bob public', 1),
  (4, '22222222-2222-4222-8222-222222222222', 'bob private', 0);
